---
# tasks file for oozie
- name: install oozie (RedHat)
  become: yes
  become_user: root
  yum: pkg={{ item }} state=present
  with_items:
    - mapr-oozie-{{oozie_version}}.{{oozie_build}}
  when: ansible_distribution in ('CentOS','RedHat','Amazon')
  notify: reconfigure roles

- name: get zookeeper ensemble
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: maprcli node listzookeepers -noheader
  register: zookeepers
  changed_when: false

- name: update oozie.services.ext
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: "/opt/mapr/oozie/oozie-{{oozie_version}}/conf/oozie-site.xml"
    name: "oozie.services.ext"
    value: "org.apache.oozie.service.ZKLocksService, org.apache.oozie.service.ZKXLogStreamingService, org.apache.oozie.service.ZKJobsConcurrencyService"
  notify: restart oozie

- name: update oozie with ZK info
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: "/opt/mapr/oozie/oozie-{{oozie_version}}/conf/oozie-site.xml"
    name: "oozie.zookeeper.connection.string"
    value: "{{zookeepers.stdout|trim}}"
  notify: restart oozie

- name: update oozie namespace
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: "/opt/mapr/oozie/oozie-{{oozie_version}}/conf/oozie-site.xml"
    name: "oozie.zookeeper.namespace"
    value: oozie
  notify: restart oozie

- name: update oozie-site.xml for impersonation (hosts)
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: "/opt/mapr/oozie/oozie-{{oozie_version}}/conf/oozie-site.xml"
    name: 'oozie.service.ProxyUserService.proxyuser.mapr.hosts'
    value: '*'
  register: proxyuser_hosts
  notify: restart oozie

- name: update oozie-site.xml for impersonation (groups)
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: "/opt/mapr/oozie/oozie-{{oozie_version}}/conf/oozie-site.xml"
    name: 'oozie.service.ProxyUserService.proxyuser.mapr.groups'
    value: '*'
  notify: restart oozie

- name: create tmp destination for oozie examples
  become: yes
  become_user: '{{mapr_admin_username}}'
  file: state=directory path="/tmp/oozie" mode=0755

- name: extract oozie examples
  become: yes
  become_user: '{{mapr_admin_username}}'
  unarchive: copy=no src=/opt/mapr/oozie/oozie-{{oozie_version}}/oozie-examples.tar.gz dest=/tmp/oozie

- name: create oozie/share/lib in dfs
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: hadoop fs -mkdir -p /oozie/share/lib/examples

- pause: seconds=20

- name: copy oozie examples to cluster
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: hadoop fs -copyFromLocal -f /tmp/oozie/examples /oozie/share/lib
