---
# handlers file for oozie
- name: reconfigure roles
  sudo: yes
  sudo_user: root
  command: /opt/mapr/server/configure.sh -R

- name: restart oozie
  sudo: yes
  sudo_user: '{{mapr_admin_username}}'
  command: maprcli node services -action restart -name oozie -filter csvc==oozie
