---
# handlers file for oozie
- name: reconfigure roles
  become: yes
  become_user: root
  command: /opt/mapr/server/configure.sh -R

- name: restart oozie
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: maprcli node services -action restart -name oozie -filter csvc==oozie
